[tools]
python = "3.14.6"
poetry = "2.4.1"

[tasks.setup]
run = "poetry install"

[tasks.notebooks]
depends = ["setup"]
run = "poetry run jupyter notebook notebooks"

[tasks.ci]
depends = ["setup"]
run = "poetry run pre-commit run --all-files"
