---
name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v7

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Run ci checks
        run: mise ci
